
server:
  port: 5000

files:
  temp_dir: _temp
  delete_durations_minutes: 100

tasks:
  duration: 5

printers:
  octopi-prusa-001:
    host: octopi-prusa-001
    key: F84833BA940E49648F606EA561E97783
  octopi-prusa-002:
    host: octopi-prusa-002
    key: F84833BA940E49648F606EA561E97783

# OAUTH_CLIENT_ID=makerspace_printer_kiosk
# OAUTH_CLIENT_SECRET=EBPNkvB9Yc4JhLT4vDqu94OkwNmd5L8W