version: "3"

services:
  frontend_api:
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./config.yml:/app/config.yml
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "100k"
