server:
  port: 5000

files:
  temp_dir: _temp
  delete_durations_minutes: 10

tasks:
  duration: 5

printers:
  octopi-prusa-001:
    host: octopi-prusa-001
    key: <<API KEY>>
  octopi-prusa-002:
    host: octopi-prusa-002
    key: <<API KEY>>
    image: <<path to printer image>>  # optional

logging:
  level: info

slicer:
  path: /prusa/prusa-slicer